import React from "react";

export const metadata = {
  title: "Sub About",
  description: "Generated by create next app",
};

export default function SubAbout() {
  // throw new Error("Something went wrong!!!");
  return <div>SubAbout</div>;
}
